networks:
  ft-net:
    external: true

volumes:
  ft-db-data:
    external: true

services:
  ft-db:
    image: postgres:16
    container_name: ft-db
    env_file: &env
      - .env.test
    volumes:
      - ft-db-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks: &network
      - ft-net
    ports:
      - "0.0.0.0:${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"
    restart: &restart unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: [ "CMD-SHELL", "PGUSER=$${POSTGRES_USER} PGDATABASE=$${POSTGRES_DB} pg_isready  || (echo 'Unhealthy, exiting...' && kill 1)" ]
      interval: 10s
      timeout: 5s
      retries: 3


  ft-backend:
    image: begenFys/fastapi-template:latest
    container_name: ft-backend
    env_file: *env
    restart: *restart
    networks: *network
    depends_on:
      ft-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://0.0.0.0:$${PORT}/api/health || (echo 'Unhealthy, exiting...' && kill 1)" ]
      interval: 60s
      timeout: 5s
      retries: 3
