networks:
  ft-test:
    external: true

volumes:
  ft-db-test-data:
    external: true

services:
  ft-db-test:
    image: postgres:16
    container_name: ft-db-test
    env_file: &env
      - .env.test
    volumes:
      - ft-db-test-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks: &network
      - ft-test
    ports:
      - "0.0.0.0:${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"
    restart: &restart unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: [ "CMD-SHELL", "PGUSER=$${POSTGRES_USER} PGDATABASE=$${POSTGRES_DB} pg_isready  || (echo 'Unhealthy, exiting...' && kill 1)" ]
      interval: 10s
      timeout: 5s
      retries: 3


  ft-backend-test:
    image: begenFys/fastapi-template:test
    container_name: ft-backend-test
    env_file: *env
    restart: *restart
    networks: *network
    ports:
      - "0.0.0.0:${BACKEND_HOST_PORT}:${PORT}"
    depends_on:
      ft-db-test:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://0.0.0.0:$${PORT}/api/health || (echo 'Unhealthy, exiting...' && kill 1)" ]
      interval: 60s
      timeout: 5s
      retries: 3
